#!/bin/bash
# Build "Beat Thief.app" - the double-clickable launcher for the GUI.
#
#   ./make_app.sh              -> builds into ~/Applications
#   ./make_app.sh /some/dir    -> builds somewhere else
#
# Why the app carries a copy of the code instead of just pointing at this
# folder, which would be simpler:
#
# macOS (TCC) blocks apps from reading ~/Desktop, ~/Documents and ~/Downloads
# without permission, and this repo lives in one of them. Granting the app
# access doesn't help - the file reads are attributed to the python3 binary
# doing them, not to the bundle around it, so the permission checkbox for
# the app covers nothing. A launcher that pointed here would fail every
# time with "Operation not permitted".
#
# So the bundle copies in what it needs and runs from inside itself, which
# needs no permission at all, and it's installed to ~/Applications, which
# isn't a protected folder. The GUI's downloads go to ~/Music/Beat Thief for
# the same reason (see gui.py) - ~/Downloads would be blocked.
#
# The tradeoff: the app holds a snapshot. Re-run this after changing any
# Python or UI file. The terminal front end (beat_thief.py) always runs the
# live code and is unaffected.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST="${1:-$HOME/Applications}"
APP="$DEST/Beat Thief.app"
PYTHON="$(command -v python3)"

# /usr/bin/python3 is a universal binary, and launched from an app bundle
# macOS picks its x86_64 slice - which then can't load this machine's arm64
# numpy/torch, failing with a confusing "don't import numpy from its source
# directory" message. Pin the architecture this build was made on. Recorded
# now rather than checked at launch, because a process started under Rosetta
# reports the wrong answer for its own machine.
ARCH="$(uname -m)"

# Everything the GUI imports, directly or indirectly.
SOURCES=(
    gui.py
    pipeline.py
    song_sanitizer.py
    instrument_isolator.py
    drum_isolator.py
    bass_isolator.py
    harmony_isolator.py
)

case "$DEST" in
    "$HOME"/Desktop/*|"$HOME"/Documents/*|"$HOME"/Downloads/*)
        echo "Refusing to build into $DEST - macOS blocks apps from reading" >&2
        echo "Desktop, Documents and Downloads, so the app couldn't start." >&2
        exit 1
        ;;
esac

mkdir -p "$DEST"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

for source in "${SOURCES[@]}"; do
    cp "$REPO/$source" "$APP/Contents/Resources/"
done
cp -R "$REPO/ui" "$APP/Contents/Resources/ui"

# Turn ui/logo.svg into the Dock icon. render_logo.py rasterizes it with
# its transparency intact - Quick Look's renderer would flatten the disc
# onto a white square.
WORK="$(mktemp -d)"
ICONSET="$WORK/icon.iconset"
mkdir -p "$ICONSET"

if "$PYTHON" "$REPO/render_logo.py" "$WORK/master.png" 1024 2>/dev/null; then
    for size in 16 32 128 256 512; do
        sips -z $size $size "$WORK/master.png" --out "$ICONSET/icon_${size}x${size}.png" >/dev/null 2>&1
        sips -z $((size * 2)) $((size * 2)) "$WORK/master.png" --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null 2>&1
    done
    iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/Beat Thief.icns" 2>/dev/null || true
else
    echo "Warning: could not render the icon; the app will use a generic one." >&2
fi
rm -rf "$WORK"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Beat Thief</string>
    <key>CFBundleDisplayName</key>
    <string>Beat Thief</string>
    <key>CFBundleIdentifier</key>
    <string>com.stefan.beatthief</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>Beat Thief</string>
    <key>CFBundleIconFile</key>
    <string>Beat Thief</string>
    <!-- A real app with a Dock icon and a menu bar, not a background tool. -->
    <key>LSUIElement</key>
    <false/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/Beat Thief" <<LAUNCHER
#!/bin/bash
# Generated by make_app.sh - edit that, not this.
#
# Everything is logged, and any failure to start raises a dialog. A launcher
# that does nothing when you double-click it is the worst thing this could
# do, so silence is never an outcome here.

LOG="\$HOME/Library/Logs/beat_thief.log"
mkdir -p "\$(dirname "\$LOG")"
echo "--- \$(date) ---" >> "\$LOG"

cd "\$(dirname "\$0")/../Resources" || exit 1
/usr/bin/arch -$ARCH "$PYTHON" gui.py >> "\$LOG" 2>&1
status=\$?

if [ \$status -ne 0 ]; then
    detail="\$(tail -n 3 "\$LOG" | tr '"' "'")"
    osascript -e "display dialog \"Beat Thief could not start.

\$detail

Full log: \$LOG\" with title \"Beat Thief\" buttons {\"OK\"} default button 1 with icon caution" >/dev/null 2>&1
fi

exit \$status
LAUNCHER

chmod +x "$APP/Contents/MacOS/Beat Thief"
codesign --force --deep --sign - "$APP" 2>/dev/null || true

echo "Built $APP"
echo "Double-click it, or drag it to your Dock."
echo
echo "It holds a copy of the code, so re-run this after editing any .py or"
echo "the UI. Downloads land in ~/Music/Beat Thief."
